Repository metwork-framework/docker-mfxxx-centos7-buildimage, pull requests merged in 2018-10, with the labels that each got.

#5 chore: fix indentation problem
  .drone.yml
Labels: Priority: High, Status: Accepted, Status: Review Needed

#6 chore: limit branch building and use conditional downstream
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#7 chore: update buildimage hash (in case mfcom has changed)
  Dockerfile
Labels: Status: Review Needed, Type: To Categorize

#8 build: better cache invalidation
  Dockerfile
Labels: Status: Review Needed

#9 chore: add trigger mfsysmon
  .drone.yml
Labels: Status: Review Needed

#11 build: move specific part of README
  .metwork-framework/README.md
Labels: Status: Review Needed
